### ISSUE TITLE
from pymemuc import PyMemuc

### ISSUE THREAD

**Issue by vitalisc** [martinmiglio/pymemuc#25]
the above e command shows this error 
 https://prnt.sc/YNHNqWc0MOIs
 please how do i fix that

**Comment by martinmiglio** [comment]
Thanks for raising this issue! It appears to be caused by a problem with the type annotations used in this module. 

I've made a fix, could you try it out by installing it from the `patch/tuple-types` branch? If you're using pip:
```bash
pip install git+https://github.com/martinmiglio/pymemuc.git@patch/tuple-types#egg=pymemuc
```
or if you're using poetry with a `pyproject.toml`, add this line to your dependencies:
```toml
pymemuc = { git = "https://github.com/martinmiglio/pymemuc.git", branch = "patch/tuple-types" }
```

Let me know if that fixes this issue and i will pull it into the main branch!
If this doesn't end up fixing your issue, could you let me know your python interpreter version?
